---
- name: Create EC2 machines
  hosts: localhost
  connection: local

  vars:
    sg_id: sg-0d4ec8455aa672dab
    ami_id: ami-0220d79f3f480ecf5
    env: dev

    instances:
      - mongodb
      - catalogue

  tasks:
    - name: Create EC2 instances
      amazon.aws.ec2_instance:
        name: "{{ item }}-{{ env }}"
        instance_type: t3.micro
        image_id: "{{ ami_id }}"
        security_group: "{{ sg_id }}"
        tags:
          project: roboshop
          Component: "{{ item }}"
          Environment: "{{ env }}"
          Name: "{{ item }}-{{ env }}"
      loop: "{{ instances }}"
      register: ec2_output

    - name: Show output
      ansible.builtin.debug:
        var: ec2_output

    - name: print the output
      ansible.builtin.debug:
        msg: "{{ ec2_output }}"    