- name: error hadling
  hosts: local
  connection: local
  tasks:
   -name: user available or not
   ansible.builtin.command: id roboshop
   register: user_output
   ignore_errors: true

-  name: print the values
   ansible.builtin.debug:
     msg: "{{ user_output}}"