- name: install mysql server
  hosts: local 
  connection: local
  become: yes
  tasks:
  - name: install web mysql server
    ansible.builtin.package:
     name: mysql
     state: present

  - name: start mysql
    ansible.builtin.service:
     name: mysql
     state: started
     enabled: yes   