- name: facts gather # when Ansible master server is connection to Node server gather the information
  hosts: local
  connection: local
  tasks:
  - name: print facts
    ansible.builtin.debug:
      msg: "{{ ansible_facts }}"